general {
    grace = 0
    immediate_render = true
    no_fade_in = false 
    disable_loading_bar = false
    hide_cursor = true
    ignore_empty_input = true
    fractional_scaling = 0
}

background {
    path = /home/elysian/Pictures/Wallpapers/kojiro.png
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}


# Time
label { 
    text = cmd[update:1000] echo "$(date +'%k:%M')"
    color = rgba(216, 222, 233, 0.7)
    font_size = 85
    font_family = JetBrainsMono Bold
    position = 0, 310
    halign = center 
    valign = center
}

# Day-Month-Date
label {
    text = cmd[update:1000] echo -e "$(date +'%A, %B %d')"
    color = rgba(216, 222, 233, 0.7)
    font_size = 30
    font_family = JetBrainsMono Bold 
    position = 0, 400
    halign = center 
    valign = center
}

# Profile-Photo
image {
    path = /home/elysian/Pictures/artemis.png
    border_color = 0xffdddddd
    border_size = 0
    size = 220
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, -185
    halign = center
    valign = center
}

# User
label {
    text =  $USER
    color = rgba(216, 222, 233, 0.7)
    font_size = 22
    font_family = JetBrainsMono Bold
    position = 0, -350
    halign = center
    valign = center
}

input-field {
    size = 170, 45
    rounding = 0
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true
    font_color = rgba(200, 200, 200)
    font_family = JetBrainsMono Bold

    outer_color = rgba(200, 200, 200)
    inner_color = rgba(100, 112, 125, 0.4)
    check_color = rgba(152, 151, 26, 0.95)
    fail_color = rgba(204, 36, 29, 0.95)
    capslock_color = rgba(215, 153, 33, 0.95)
    bothlock_color = rgba(215, 153, 33, 0.95)

    hide_input = false
    fade_on_empty = false
    placeholder_text = <i><span foreground="##fbf1c7">Enter Password</span></i>

    position = 0, -425
    halign = center
    valign = center
}

animation = inputFieldColors, 0 

